<?php
// $Id$

/**
 * @file
 * Implementation of module administration pages.
 */

/**
 * Build the module settings form.
 */
function dirtyforms_admin_settings() {
  $form = array();
  // @TODO
  return $form;
}

/**
 * Validate handler for the module settings form.
 */
function dirtyforms_admin_settings_validate($form, &$form_state) {
  // @TODO
}

/**
 * Submit handler for the module settings form.
 */
function dirtyforms_admin_settings_submit($form, &$form_state) {
  // @TODO
}
